# Generated by Django 6.0.6 on 2026-07-05 14:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0002_alter_distributeur_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('idcommande', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro')),
                ('date_commande', models.DateField(verbose_name='Date de la commande')),
                ('montant_brut', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant brut')),
                ('montant_net', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant net')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('point_vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='referentiel.pointvente', verbose_name='Point de vente')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'commande',
                'ordering': ['-date_commande', '-idcommande'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('idlignecommande', models.AutoField(primary_key=True, serialize=False)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('taux_remise', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('montant_remise', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('montant_net', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='referentiel.produit')),
            ],
            options={
                'verbose_name': 'Ligne commande',
                'verbose_name_plural': 'Lignes commande',
                'db_table': 'lignecommande',
                'ordering': ['produit__designation'],
                'constraints': [models.UniqueConstraint(fields=('commande', 'produit'), name='produit_unique_commande')],
            },
        ),
    ]
