# Generated by Django 6.0.6 on 2026-07-06 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
        ('referentiel', '0002_alter_distributeur_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='etat',
            field=models.CharField(choices=[('ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], default='ATTENTE', max_length=20, verbose_name='Etat'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['etat'], name='commande_etat_b83b01_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['date_commande'], name='commande_date_co_af0bf2_idx'),
        ),
    ]
