# Generated by Django 6.0.6 on 2026-07-06 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_commande_etat_commande_commande_etat_b83b01_idx_and_more'),
        ('referentiel', '0002_alter_distributeur_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='commande',
            name='type_commande',
            field=models.CharField(choices=[('DIRECTEUR', 'Commande Directeur'), ('GERANT', 'Commande Gérant')], default='GERANT', max_length=20, verbose_name='Type de commande'),
        ),
        migrations.AddField(
            model_name='commande',
            name='utilisateur_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['type_commande'], name='commande_type_co_5ec9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['point_vente'], name='commande_point_v_d20eee_idx'),
        ),
    ]
