# Generated by Django 6.0.6 on 2026-07-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_date_validation_commande_type_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='categorie_commande',
            field=models.CharField(choices=[('NORMALE', 'Commande normale'), ('STOCK_TAMPON', 'Commande stock tampon'), ('CAUTION', 'Commande caution bancaire'), ('REGLEMENT_STOCK', 'Règlement stock tampon')], default='NORMALE', max_length=30, verbose_name='Catégorie'),
        ),
    ]
