# Generated by Django 6.0.6 on 2026-07-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_commande_categorie_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='quantite_distribuee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='commande',
            name='etat',
            field=models.CharField(choices=[('ATTENTE', 'En attente'), ('VALIDEE_PARTIELLEMENT', 'Validée partiellement'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], default='ATTENTE', max_length=30, verbose_name='Etat'),
        ),
    ]
