# Generated by Django 6.0.6 on 2026-07-03 07:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0002_alter_distributeur_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('idobjectif', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(editable=False, max_length=150, verbose_name='Désignation')),
                ('mois', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois')),
                ('annee', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2025), django.core.validators.MaxValueValidator(2100)], verbose_name='Année')),
                ('montant_cible', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Montant cible')),
                ('montant_realise', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant réalisé')),
                ('taux_realise', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Taux réalisé')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objectifs', to='referentiel.compagnie', verbose_name='Compagnie')),
                ('point_vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objectifs', to='referentiel.pointvente', verbose_name='Point de vente')),
            ],
            options={
                'verbose_name': 'Objectif',
                'verbose_name_plural': 'Objectifs',
                'db_table': 'objectif',
                'ordering': ['-annee', '-mois', 'designation'],
            },
        ),
        migrations.CreateModel(
            name='LigneObjectif',
            fields=[
                ('idligneobjectif', models.AutoField(primary_key=True, serialize=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_objectifs', to='referentiel.produit', verbose_name='Produit')),
                ('objectif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='objectif.objectif', verbose_name='Objectif')),
            ],
            options={
                'verbose_name': 'Ligne objectif',
                'verbose_name_plural': 'Lignes objectifs',
                'db_table': 'ligneobjectif',
            },
        ),
        migrations.AddConstraint(
            model_name='objectif',
            constraint=models.UniqueConstraint(fields=('compagnie', 'point_vente', 'mois', 'annee'), name='objectif_unique'),
        ),
        migrations.AddConstraint(
            model_name='ligneobjectif',
            constraint=models.UniqueConstraint(fields=('objectif', 'produit'), name='produit_unique_objectif'),
        ),
    ]
