# Generated by Django 6.0.6 on 2026-06-23 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('idcompagnie', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=150, unique=True, verbose_name='Désignation')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compagnie',
                'verbose_name_plural': 'Compagnies',
                'db_table': 'compagnie',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='PointVente',
            fields=[
                ('idpointvente', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=150, unique=True, verbose_name='Désignation')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Point de vente',
                'verbose_name_plural': 'Points de vente',
                'db_table': 'pointvente',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='Distributeur',
            fields=[
                ('iddistributeur', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='TEMP', max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('point_vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributeurs', to='referentiel.pointvente', verbose_name='Point de vente')),
            ],
            options={
                'verbose_name': 'Distributeur',
                'verbose_name_plural': 'Distributeurs',
                'db_table': 'distributeur',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('idproduit', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=150, verbose_name='Désignation')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Prix')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='referentiel.compagnie', verbose_name='Compagnie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'produit',
                'ordering': ['designation'],
            },
        ),
    ]
