# Generated by Django 6.0.6 on 2026-07-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributeur',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
