# Generated by Django 6.0.6 on 2026-07-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0002_alter_distributeur_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributeur',
            name='categorie',
            field=models.CharField(choices=[('GERANT', 'Gérant'), ('DISTRIBUTEUR', 'Distributeur'), ('CLIENT', 'Client')], default='DISTRIBUTEUR', max_length=20, verbose_name='Catégorie'),
        ),
    ]
