# Generated by Django 6.0.6 on 2026-08-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0003_distributeur_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributeur',
            name='fond',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Fond'),
        ),
    ]
