# Generated by Django 6.0.6 on 2026-07-24 22:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0005_lignecommande_quantite_distribuee_and_more'),
        ('referentiel', '0002_alter_distributeur_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('iddistribution', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro')),
                ('type_distribution', models.CharField(choices=[('COMMANDE_GERANT', 'Commande gérant'), ('DISTRIBUTEUR', 'Distributeur'), ('CLIENT_DIRECT', 'Client direct')], max_length=30, verbose_name='Type de distribution')),
                ('date_distribution', models.DateField(verbose_name='Date de distribution')),
                ('montant_brut', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant brut')),
                ('montant_net', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant net')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='commandes.commande', verbose_name='Commande')),
                ('distributeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='referentiel.distributeur', verbose_name='Distributeur')),
                ('point_vente_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributions_destination', to='referentiel.pointvente')),
                ('point_vente_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions_source', to='referentiel.pointvente')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Distribution',
                'verbose_name_plural': 'Distributions',
                'db_table': 'distribution',
                'ordering': ['-date_distribution', '-iddistribution'],
            },
        ),
        migrations.CreateModel(
            name='LigneDistribution',
            fields=[
                ('idlignedistribution', models.AutoField(primary_key=True, serialize=False)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('taux_remise', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('montant_remise', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('montant_net', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='distributions.distribution')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_distribution', to='referentiel.produit')),
            ],
            options={
                'verbose_name': 'Ligne distribution',
                'verbose_name_plural': 'Lignes distribution',
                'db_table': 'lignedistribution',
                'ordering': ['produit__designation'],
            },
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['date_distribution'], name='distributio_date_di_0963a1_idx'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['point_vente_source'], name='distributio_point_v_a28bca_idx'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['point_vente_destination'], name='distributio_point_v_9986fd_idx'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['type_distribution'], name='distributio_type_di_894b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['distributeur'], name='distributio_distrib_4299fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='lignedistribution',
            constraint=models.UniqueConstraint(fields=('distribution', 'produit'), name='produit_unique_distribution'),
        ),
    ]
