# Generated by Codex on 2026-08-22

from django.db import migrations, models


def cloturer_distributions_deja_situees(apps, schema_editor):
    Distribution = apps.get_model(
        "distributions",
        "Distribution"
    )

    SituationJournaliere = apps.get_model(
        "situations",
        "SituationJournaliere"
    )

    situations = (
        SituationJournaliere.objects
        .filter(
            etat="CLOTUREE",
            actif=True,
        )
        .values(
            "distributeur_id",
            "date_situation",
        )
    )

    for situation in situations:

        Distribution.objects.filter(
            distributeur_id=situation["distributeur_id"],
            date_distribution=situation["date_situation"],
            actif=True,
        ).update(
            etat="CLOTUREE"
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "distributions",
            "0001_initial"
        ),
        (
            "situations",
            "0005_lignesituationjournaliere_taux_remise"
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="etat",
            field=models.CharField(
                choices=[
                    (
                        "OUVERTE",
                        "Ouverte"
                    ),
                    (
                        "CLOTUREE",
                        "Clôturée"
                    ),
                ],
                default="OUVERTE",
                max_length=20,
                verbose_name="Etat"
            ),
        ),
        migrations.AddIndex(
            model_name="distribution",
            index=models.Index(
                fields=[
                    "etat"
                ],
                name="distribution_etat_idx"
            ),
        ),
        migrations.RunPython(
            cloturer_distributions_deja_situees,
            migrations.RunPython.noop
        ),
    ]
