\set ON_ERROR_STOP on

-- ============================================================================
-- EMG Manage - schema PostgreSQL de reference (version 2)
-- PostgreSQL 18+
--
-- IMPORTANT
-- 1. Ce script est prevu pour une installation neuve dans le schema "emg".
-- 2. Il ne supprime et ne modifie aucune ancienne table du schema "public".
-- 3. Ne pas l'executer sur bd_emg avant l'audit et la sauvegarde des donnees.
-- 4. Avec Django, les modeles et migrations devront rester la source officielle.
--
-- Execution future, apres validation explicite :
--   psql -U postgres -d bd_emg -f database/schema_emg_v2.sql
--
-- REMISE A ZERO DESTRUCTIVE DU NOUVEAU SCHEMA (laissee commentee) :
--   DROP SCHEMA IF EXISTS emg CASCADE;
-- ============================================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS emg;
SET search_path TO emg, public;

-- ============================================================================
-- Fonctions techniques communes
-- ============================================================================

CREATE OR REPLACE FUNCTION emg.fn_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION emg.fn_document_modifiable()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.statut <> 'BROUILLON' THEN
        RAISE EXCEPTION 'Le document % est %, il est donc immutable.', OLD.id, OLD.statut;
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION emg.fn_ligne_document_modifiable()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_parent_id bigint;
    v_statut varchar(20);
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_parent_id := (to_jsonb(OLD) ->> TG_ARGV[1])::bigint;
    ELSE
        v_parent_id := (to_jsonb(NEW) ->> TG_ARGV[1])::bigint;
    END IF;

    EXECUTE format('SELECT statut FROM emg.%I WHERE id = $1', TG_ARGV[0])
       INTO v_statut
       USING v_parent_id;

    -- Lors d'un ON DELETE CASCADE, le parent peut deja ne plus etre visible.
    IF v_statut IS NULL AND TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    IF v_statut IS NULL THEN
        RAISE EXCEPTION 'Document parent % introuvable.', v_parent_id;
    END IF;

    IF v_statut <> 'BROUILLON' THEN
        RAISE EXCEPTION 'Les lignes du document % ne sont plus modifiables.', v_parent_id;
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$$;

-- ============================================================================
-- Referentiel, utilisateurs et droits metier
-- ============================================================================

CREATE TABLE emg.point_vente (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    designation varchar(150) NOT NULL,
    adresse varchar(255) NOT NULL,
    type varchar(20) NOT NULL,
    actif boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_point_vente_type
        CHECK (type IN ('CENTRAL', 'POINT_VENTE')),
    CONSTRAINT ck_point_vente_designation_non_vide
        CHECK (btrim(designation) <> '')
);

CREATE UNIQUE INDEX uq_point_vente_designation_ci
    ON emg.point_vente (lower(designation));

CREATE UNIQUE INDEX uq_point_vente_un_seul_central
    ON emg.point_vente (type)
    WHERE type = 'CENTRAL';

CREATE TRIGGER trg_point_vente_updated_at
BEFORE UPDATE ON emg.point_vente
FOR EACH ROW EXECUTE FUNCTION emg.fn_set_updated_at();

-- Cette table reprend les champs principaux d'un AbstractUser Django.
-- Les tables auth_group, auth_permission et les tables M2M seront gerees
-- par les migrations Django, pas manuellement dans ce script de domaine.
CREATE TABLE emg.utilisateur (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password varchar(128) NOT NULL,
    last_login timestamptz,
    is_superuser boolean NOT NULL DEFAULT false,
    username varchar(150) NOT NULL,
    first_name varchar(150) NOT NULL DEFAULT '',
    last_name varchar(150) NOT NULL DEFAULT '',
    email varchar(254) NOT NULL DEFAULT '',
    is_staff boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    date_joined timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    telephone varchar(30) NOT NULL,
    role varchar(20) NOT NULL,
    idpointvente bigint,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_utilisateur_point_vente
        FOREIGN KEY (idpointvente) REFERENCES emg.point_vente(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ck_utilisateur_role
        CHECK (role IN ('ADMINISTRATEUR', 'DIRECTEUR', 'GERANT')),
    CONSTRAINT ck_utilisateur_point_requis
        CHECK (role = 'ADMINISTRATEUR' OR idpointvente IS NOT NULL),
    CONSTRAINT ck_utilisateur_username_non_vide
        CHECK (btrim(username) <> ''),
    CONSTRAINT ck_utilisateur_telephone_non_vide
        CHECK (btrim(telephone) <> '')
);

CREATE UNIQUE INDEX uq_utilisateur_username_ci
    ON emg.utilisateur (lower(username));

CREATE UNIQUE INDEX uq_utilisateur_telephone
    ON emg.utilisateur (telephone);

CREATE INDEX idx_utilisateur_point_vente
    ON emg.utilisateur (idpointvente);

CREATE OR REPLACE FUNCTION emg.fn_verifier_role_point_vente()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_type varchar(20);
BEGIN
    IF NEW.role = 'ADMINISTRATEUR' AND NEW.idpointvente IS NULL THEN
        RETURN NEW;
    END IF;

    SELECT type INTO v_type
    FROM emg.point_vente
    WHERE id = NEW.idpointvente AND actif = true;

    IF v_type IS NULL THEN
        RAISE EXCEPTION 'Le point de vente doit exister et etre actif.';
    END IF;

    IF NEW.role = 'DIRECTEUR' AND v_type <> 'CENTRAL' THEN
        RAISE EXCEPTION 'Un directeur doit etre rattache au point CENTRAL.';
    END IF;

    IF NEW.role = 'GERANT' AND v_type <> 'POINT_VENTE' THEN
        RAISE EXCEPTION 'Un gerant doit etre rattache a un point de vente non central.';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_utilisateur_role_point
BEFORE INSERT OR UPDATE OF role, idpointvente ON emg.utilisateur
FOR EACH ROW EXECUTE FUNCTION emg.fn_verifier_role_point_vente();

CREATE TRIGGER trg_utilisateur_updated_at
BEFORE UPDATE ON emg.utilisateur
FOR EACH ROW EXECUTE FUNCTION emg.fn_set_updated_at();

CREATE TABLE emg.revendeur (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom varchar(100) NOT NULL,
    prenom varchar(100) NOT NULL DEFAULT '',
    telephone varchar(30),
    idpointvente bigint NOT NULL,
    actif boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_revendeur_point_vente
        FOREIGN KEY (idpointvente) REFERENCES emg.point_vente(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ck_revendeur_nom_non_vide CHECK (btrim(nom) <> '')
);

CREATE INDEX idx_revendeur_point_vente
    ON emg.revendeur (idpointvente);

CREATE UNIQUE INDEX uq_revendeur_point_telephone
    ON emg.revendeur (idpointvente, telephone)
    WHERE telephone IS NOT NULL;

CREATE TRIGGER trg_revendeur_updated_at
BEFORE UPDATE ON emg.revendeur
FOR EACH ROW EXECUTE FUNCTION emg.fn_set_updated_at();

CREATE TABLE emg.compagnie (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    designation varchar(150) NOT NULL,
    actif boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_compagnie_designation_non_vide CHECK (btrim(designation) <> '')
);

CREATE UNIQUE INDEX uq_compagnie_designation_ci
    ON emg.compagnie (lower(designation));

CREATE TRIGGER trg_compagnie_updated_at
BEFORE UPDATE ON emg.compagnie
FOR EACH ROW EXECUTE FUNCTION emg.fn_set_updated_at();

CREATE TABLE emg.groupe_produit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idcompagnie bigint NOT NULL,
    designation varchar(150) NOT NULL,
    actif boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_groupe_produit_compagnie
        FOREIGN KEY (idcompagnie) REFERENCES emg.compagnie(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ck_groupe_produit_designation_non_vide CHECK (btrim(designation) <> '')
);

CREATE UNIQUE INDEX uq_groupe_produit_compagnie_designation_ci
    ON emg.groupe_produit (idcompagnie, lower(designation));

CREATE INDEX idx_groupe_produit_compagnie
    ON emg.groupe_produit (idcompagnie);

CREATE TRIGGER trg_groupe_produit_updated_at
BEFORE UPDATE ON emg.groupe_produit
FOR EACH ROW EXECUTE FUNCTION emg.fn_set_updated_at();

CREATE TABLE emg.produit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idgroupe_produit bigint NOT NULL,
    designation varchar(150) NOT NULL,
    valeur_nominale numeric(18,2) NOT NULL,
    actif boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_produit_groupe
        FOREIGN KEY (idgroupe_produit) REFERENCES emg.groupe_produit(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ck_produit_valeur_nominale CHECK (valeur_nominale >= 0),
    CONSTRAINT ck_produit_designation_non_vide CHECK (btrim(designation) <> '')
);

CREATE UNIQUE INDEX uq_produit_groupe_designation_ci
    ON emg.produit (idgroupe_produit, lower(designation));

CREATE INDEX idx_produit_groupe
    ON emg.produit (idgroupe_produit);

CREATE TRIGGER trg_produit_updated_at
BEFORE UPDATE ON emg.produit
FOR EACH ROW EXECUTE FUNCTION emg.fn_set_updated_at();

-- ============================================================================
-- Stock et journal immutable des mouvements
-- ============================================================================

CREATE TABLE emg.stock (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idpointvente bigint NOT NULL,
    idproduit bigint NOT NULL,
    type_stock varchar(10) NOT NULL,
    quantite bigint NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stock_point_vente
        FOREIGN KEY (idpointvente) REFERENCES emg.point_vente(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_stock_produit
        FOREIGN KEY (idproduit) REFERENCES emg.produit(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_stock_point_produit_type
        UNIQUE (idpointvente, idproduit, type_stock),
    CONSTRAINT ck_stock_type CHECK (type_stock IN ('NORMAL', 'TAMPON')),
    CONSTRAINT ck_stock_quantite CHECK (quantite >= 0)
);

CREATE INDEX idx_stock_produit ON emg.stock (idproduit);
CREATE INDEX idx_stock_point_vente ON emg.stock (idpointvente);

CREATE TABLE emg.operation_stock (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_operation varchar(30) NOT NULL,
    date_operation timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reference_metier varchar(100),
    idutilisateur bigint NOT NULL,
    idoperation_origine bigint,
    commentaire text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_operation_stock_utilisateur
        FOREIGN KEY (idutilisateur) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_operation_stock_origine
        FOREIGN KEY (idoperation_origine) REFERENCES emg.operation_stock(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ck_operation_stock_type CHECK (
        type_operation IN (
            'RECEPTION_COMMANDE',
            'TRANSFERT_TAMPON',
            'LIVRAISON_POINT_VENTE',
            'DISTRIBUTION_REVENDEUR',
            'AJUSTEMENT_INVENTAIRE',
            'ANNULATION'
        )
    ),
    CONSTRAINT ck_operation_stock_annulation CHECK (
        (type_operation = 'ANNULATION' AND idoperation_origine IS NOT NULL)
        OR
        (type_operation <> 'ANNULATION' AND idoperation_origine IS NULL)
    )
);

CREATE INDEX idx_operation_stock_date ON emg.operation_stock (date_operation);
CREATE INDEX idx_operation_stock_origine ON emg.operation_stock (idoperation_origine);

CREATE TABLE emg.mouvement_stock (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idoperation_stock bigint NOT NULL,
    idpointvente bigint NOT NULL,
    idproduit bigint NOT NULL,
    type_stock varchar(10) NOT NULL,
    variation bigint NOT NULL,
    quantite_avant bigint NOT NULL,
    quantite_apres bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mouvement_operation
        FOREIGN KEY (idoperation_stock) REFERENCES emg.operation_stock(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_mouvement_point_vente
        FOREIGN KEY (idpointvente) REFERENCES emg.point_vente(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_mouvement_produit
        FOREIGN KEY (idproduit) REFERENCES emg.produit(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_mouvement_operation_stock
        UNIQUE (idoperation_stock, idpointvente, idproduit, type_stock),
    CONSTRAINT ck_mouvement_type_stock CHECK (type_stock IN ('NORMAL', 'TAMPON')),
    CONSTRAINT ck_mouvement_variation_non_nulle CHECK (variation <> 0),
    CONSTRAINT ck_mouvement_quantites CHECK (
        quantite_avant >= 0
        AND quantite_apres >= 0
        AND quantite_apres = quantite_avant + variation
    )
);

CREATE INDEX idx_mouvement_stock_operation ON emg.mouvement_stock (idoperation_stock);
CREATE INDEX idx_mouvement_stock_point_produit
    ON emg.mouvement_stock (idpointvente, idproduit, type_stock);
CREATE INDEX idx_mouvement_stock_date ON emg.mouvement_stock (created_at);

CREATE OR REPLACE FUNCTION emg.fn_verifier_stock_tampon_central()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_type_point varchar(20);
BEGIN
    IF NEW.type_stock = 'TAMPON' THEN
        SELECT type INTO v_type_point
        FROM emg.point_vente
        WHERE id = NEW.idpointvente;

        IF v_type_point <> 'CENTRAL' THEN
            RAISE EXCEPTION 'Le stock TAMPON est reserve au point CENTRAL.';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION emg.fn_proteger_stock()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF current_setting('emg.stock_write_authorized', true) IS DISTINCT FROM 'on' THEN
        RAISE EXCEPTION 'Le stock ne peut etre modifie que par un mouvement de stock.';
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION emg.fn_appliquer_mouvement_stock()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_avant bigint;
    v_apres bigint;
BEGIN
    PERFORM set_config('emg.stock_write_authorized', 'on', true);

    INSERT INTO emg.stock (idpointvente, idproduit, type_stock, quantite)
    VALUES (NEW.idpointvente, NEW.idproduit, NEW.type_stock, 0)
    ON CONFLICT (idpointvente, idproduit, type_stock) DO NOTHING;

    SELECT quantite INTO v_avant
    FROM emg.stock
    WHERE idpointvente = NEW.idpointvente
      AND idproduit = NEW.idproduit
      AND type_stock = NEW.type_stock
    FOR UPDATE;

    v_apres := v_avant + NEW.variation;

    IF v_apres < 0 THEN
        RAISE EXCEPTION
            'Stock insuffisant: point %, produit %, type %, disponible %, variation %.',
            NEW.idpointvente, NEW.idproduit, NEW.type_stock, v_avant, NEW.variation;
    END IF;

    UPDATE emg.stock
       SET quantite = v_apres,
           updated_at = CURRENT_TIMESTAMP
     WHERE idpointvente = NEW.idpointvente
       AND idproduit = NEW.idproduit
       AND type_stock = NEW.type_stock;

    NEW.quantite_avant := v_avant;
    NEW.quantite_apres := v_apres;

    PERFORM set_config('emg.stock_write_authorized', 'off', true);
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION emg.fn_ecriture_immutable()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'Cette ecriture est immutable; utilisez une contre-operation.';
END;
$$;

CREATE TRIGGER trg_stock_00_protection
BEFORE INSERT OR UPDATE OR DELETE ON emg.stock
FOR EACH ROW EXECUTE FUNCTION emg.fn_proteger_stock();

CREATE TRIGGER trg_stock_10_tampon_central
BEFORE INSERT OR UPDATE OF idpointvente, type_stock ON emg.stock
FOR EACH ROW EXECUTE FUNCTION emg.fn_verifier_stock_tampon_central();

CREATE TRIGGER trg_mouvement_00_tampon_central
BEFORE INSERT ON emg.mouvement_stock
FOR EACH ROW EXECUTE FUNCTION emg.fn_verifier_stock_tampon_central();

CREATE TRIGGER trg_mouvement_10_appliquer
BEFORE INSERT ON emg.mouvement_stock
FOR EACH ROW EXECUTE FUNCTION emg.fn_appliquer_mouvement_stock();

CREATE TRIGGER trg_mouvement_immutable
BEFORE UPDATE OR DELETE ON emg.mouvement_stock
FOR EACH ROW EXECUTE FUNCTION emg.fn_ecriture_immutable();

CREATE TRIGGER trg_operation_stock_immutable
BEFORE UPDATE OR DELETE ON emg.operation_stock
FOR EACH ROW EXECUTE FUNCTION emg.fn_ecriture_immutable();

-- ============================================================================
-- Commandes aux compagnies
-- ============================================================================

CREATE TABLE emg.commande_compagnie (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference varchar(50) NOT NULL,
    idcompagnie bigint NOT NULL,
    date_commande date NOT NULL,
    type_commande varchar(30) NOT NULL,
    statut varchar(20) NOT NULL DEFAULT 'BROUILLON',
    idoperation_stock bigint,
    idcree_par bigint NOT NULL,
    idvalide_par bigint,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    validated_at timestamptz,
    CONSTRAINT fk_commande_compagnie_compagnie
        FOREIGN KEY (idcompagnie) REFERENCES emg.compagnie(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_commande_compagnie_operation
        FOREIGN KEY (idoperation_stock) REFERENCES emg.operation_stock(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_commande_compagnie_createur
        FOREIGN KEY (idcree_par) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_commande_compagnie_validateur
        FOREIGN KEY (idvalide_par) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_commande_compagnie_reference UNIQUE (reference),
    CONSTRAINT uq_commande_compagnie_operation UNIQUE (idoperation_stock),
    CONSTRAINT ck_commande_compagnie_type CHECK (
        type_commande IN ('NORMALE', 'RENOUVELLEMENT_TAMPON', 'CAUTION_BANCAIRE')
    ),
    CONSTRAINT ck_commande_compagnie_statut
        CHECK (statut IN ('BROUILLON', 'VALIDEE', 'ANNULEE')),
    CONSTRAINT ck_commande_compagnie_validation CHECK (
        (statut = 'VALIDEE' AND idoperation_stock IS NOT NULL
                            AND idvalide_par IS NOT NULL
                            AND validated_at IS NOT NULL)
        OR statut IN ('BROUILLON', 'ANNULEE')
    )
);

CREATE INDEX idx_commande_compagnie_compagnie_date
    ON emg.commande_compagnie (idcompagnie, date_commande);
CREATE INDEX idx_commande_compagnie_statut ON emg.commande_compagnie (statut);

CREATE TABLE emg.ligne_commande_compagnie (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idcommande_compagnie bigint NOT NULL,
    idproduit bigint NOT NULL,
    quantite bigint NOT NULL,
    prix_unitaire numeric(18,2) NOT NULL,
    taux_remise_pct numeric(7,4) NOT NULL DEFAULT 0,
    reduction_fixe numeric(18,2) NOT NULL DEFAULT 0,
    montant_brut numeric(18,2) GENERATED ALWAYS AS (
        round(quantite::numeric * prix_unitaire, 2)
    ) STORED,
    montant_reduction numeric(18,2) GENERATED ALWAYS AS (
        round((quantite::numeric * prix_unitaire * taux_remise_pct / 100) + reduction_fixe, 2)
    ) STORED,
    montant_net numeric(18,2) GENERATED ALWAYS AS (
        round((quantite::numeric * prix_unitaire)
              - (quantite::numeric * prix_unitaire * taux_remise_pct / 100)
              - reduction_fixe, 2)
    ) STORED,
    CONSTRAINT fk_ligne_commande_compagnie_commande
        FOREIGN KEY (idcommande_compagnie) REFERENCES emg.commande_compagnie(id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_ligne_commande_compagnie_produit
        FOREIGN KEY (idproduit) REFERENCES emg.produit(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_ligne_commande_compagnie_produit
        UNIQUE (idcommande_compagnie, idproduit),
    CONSTRAINT ck_ligne_commande_compagnie_quantite CHECK (quantite > 0),
    CONSTRAINT ck_ligne_commande_compagnie_prix CHECK (prix_unitaire >= 0),
    CONSTRAINT ck_ligne_commande_compagnie_taux CHECK (taux_remise_pct BETWEEN 0 AND 100),
    CONSTRAINT ck_ligne_commande_compagnie_reduction CHECK (
        reduction_fixe >= 0 AND montant_net >= 0
    )
);

CREATE INDEX idx_ligne_commande_compagnie_produit
    ON emg.ligne_commande_compagnie (idproduit);

CREATE OR REPLACE FUNCTION emg.fn_verifier_produit_compagnie_commande()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_compagnie_commande bigint;
    v_compagnie_produit bigint;
BEGIN
    SELECT idcompagnie INTO v_compagnie_commande
    FROM emg.commande_compagnie
    WHERE id = NEW.idcommande_compagnie;

    SELECT gp.idcompagnie INTO v_compagnie_produit
    FROM emg.produit p
    JOIN emg.groupe_produit gp ON gp.id = p.idgroupe_produit
    WHERE p.id = NEW.idproduit;

    IF v_compagnie_commande IS DISTINCT FROM v_compagnie_produit THEN
        RAISE EXCEPTION 'Le produit ne correspond pas a la compagnie de la commande.';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_commande_compagnie_modifiable
BEFORE UPDATE OR DELETE ON emg.commande_compagnie
FOR EACH ROW EXECUTE FUNCTION emg.fn_document_modifiable();

CREATE TRIGGER trg_ligne_commande_compagnie_modifiable
BEFORE INSERT OR UPDATE OR DELETE ON emg.ligne_commande_compagnie
FOR EACH ROW EXECUTE FUNCTION emg.fn_ligne_document_modifiable(
    'commande_compagnie', 'idcommande_compagnie'
);

CREATE TRIGGER trg_ligne_commande_compagnie_produit
BEFORE INSERT OR UPDATE OF idcommande_compagnie, idproduit
ON emg.ligne_commande_compagnie
FOR EACH ROW EXECUTE FUNCTION emg.fn_verifier_produit_compagnie_commande();

-- ============================================================================
-- Commandes internes et livraisons aux points de vente
-- ============================================================================

CREATE TABLE emg.commande_point_vente (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference varchar(50) NOT NULL,
    idpointvente bigint NOT NULL,
    date_commande date NOT NULL,
    statut varchar(20) NOT NULL DEFAULT 'BROUILLON',
    idcree_par bigint NOT NULL,
    idtraite_par bigint,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at timestamptz,
    CONSTRAINT fk_commande_point_vente_point
        FOREIGN KEY (idpointvente) REFERENCES emg.point_vente(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_commande_point_vente_createur
        FOREIGN KEY (idcree_par) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_commande_point_vente_traiteur
        FOREIGN KEY (idtraite_par) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_commande_point_vente_reference UNIQUE (reference),
    CONSTRAINT ck_commande_point_vente_statut CHECK (
        statut IN ('BROUILLON', 'SOUMISE', 'PARTIELLE', 'SERVIE', 'REJETEE', 'ANNULEE')
    )
);

CREATE INDEX idx_commande_point_vente_point_date
    ON emg.commande_point_vente (idpointvente, date_commande);
CREATE INDEX idx_commande_point_vente_statut ON emg.commande_point_vente (statut);

CREATE TABLE emg.ligne_commande_point_vente (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idcommande_point_vente bigint NOT NULL,
    idproduit bigint NOT NULL,
    quantite_demandee bigint NOT NULL,
    quantite_acceptee bigint,
    CONSTRAINT fk_ligne_commande_point_commande
        FOREIGN KEY (idcommande_point_vente) REFERENCES emg.commande_point_vente(id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_ligne_commande_point_produit
        FOREIGN KEY (idproduit) REFERENCES emg.produit(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_ligne_commande_point_produit
        UNIQUE (idcommande_point_vente, idproduit),
    CONSTRAINT ck_ligne_commande_point_quantites CHECK (
        quantite_demandee > 0
        AND (quantite_acceptee IS NULL
             OR quantite_acceptee BETWEEN 0 AND quantite_demandee)
    )
);

CREATE INDEX idx_ligne_commande_point_produit
    ON emg.ligne_commande_point_vente (idproduit);

CREATE TABLE emg.livraison_point_vente (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference varchar(50) NOT NULL,
    idcommande_point_vente bigint,
    idpointvente_destination bigint NOT NULL,
    date_livraison date NOT NULL,
    statut varchar(20) NOT NULL DEFAULT 'BROUILLON',
    idoperation_stock bigint,
    idcree_par bigint NOT NULL,
    idvalide_par bigint,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    validated_at timestamptz,
    CONSTRAINT fk_livraison_commande_point
        FOREIGN KEY (idcommande_point_vente) REFERENCES emg.commande_point_vente(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_livraison_destination
        FOREIGN KEY (idpointvente_destination) REFERENCES emg.point_vente(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_livraison_operation
        FOREIGN KEY (idoperation_stock) REFERENCES emg.operation_stock(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_livraison_createur
        FOREIGN KEY (idcree_par) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_livraison_validateur
        FOREIGN KEY (idvalide_par) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_livraison_reference UNIQUE (reference),
    CONSTRAINT uq_livraison_operation UNIQUE (idoperation_stock),
    CONSTRAINT ck_livraison_statut
        CHECK (statut IN ('BROUILLON', 'VALIDEE', 'ANNULEE')),
    CONSTRAINT ck_livraison_validation CHECK (
        (statut = 'VALIDEE' AND idoperation_stock IS NOT NULL
                            AND idvalide_par IS NOT NULL
                            AND validated_at IS NOT NULL)
        OR statut IN ('BROUILLON', 'ANNULEE')
    )
);

CREATE INDEX idx_livraison_destination_date
    ON emg.livraison_point_vente (idpointvente_destination, date_livraison);
CREATE INDEX idx_livraison_commande
    ON emg.livraison_point_vente (idcommande_point_vente);

CREATE TABLE emg.ligne_livraison_point_vente (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idlivraison_point_vente bigint NOT NULL,
    idproduit bigint NOT NULL,
    quantite bigint NOT NULL,
    CONSTRAINT fk_ligne_livraison_livraison
        FOREIGN KEY (idlivraison_point_vente) REFERENCES emg.livraison_point_vente(id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_ligne_livraison_produit
        FOREIGN KEY (idproduit) REFERENCES emg.produit(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_ligne_livraison_produit
        UNIQUE (idlivraison_point_vente, idproduit),
    CONSTRAINT ck_ligne_livraison_quantite CHECK (quantite > 0)
);

CREATE INDEX idx_ligne_livraison_produit
    ON emg.ligne_livraison_point_vente (idproduit);

CREATE OR REPLACE FUNCTION emg.fn_verifier_livraison_destination()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_type varchar(20);
    v_point_commande bigint;
BEGIN
    SELECT type INTO v_type
    FROM emg.point_vente
    WHERE id = NEW.idpointvente_destination;

    IF v_type <> 'POINT_VENTE' THEN
        RAISE EXCEPTION 'La destination d''une livraison doit etre un point non central.';
    END IF;

    IF NEW.idcommande_point_vente IS NOT NULL THEN
        SELECT idpointvente INTO v_point_commande
        FROM emg.commande_point_vente
        WHERE id = NEW.idcommande_point_vente;

        IF v_point_commande IS DISTINCT FROM NEW.idpointvente_destination THEN
            RAISE EXCEPTION 'La livraison et la commande doivent concerner le meme point.';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION emg.fn_commande_point_modifiable()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.statut <> 'BROUILLON' THEN
            RAISE EXCEPTION 'Seule une commande interne brouillon peut etre supprimee.';
        END IF;
        RETURN OLD;
    END IF;

    IF OLD.statut IN ('SERVIE', 'REJETEE', 'ANNULEE') THEN
        RAISE EXCEPTION 'La commande interne % est cloturee.', OLD.id;
    END IF;

    IF OLD.statut <> 'BROUILLON' AND (
        NEW.reference IS DISTINCT FROM OLD.reference
        OR NEW.idpointvente IS DISTINCT FROM OLD.idpointvente
        OR NEW.date_commande IS DISTINCT FROM OLD.date_commande
        OR NEW.idcree_par IS DISTINCT FROM OLD.idcree_par
    ) THEN
        RAISE EXCEPTION 'Les donnees principales ne changent plus apres soumission.';
    END IF;

    IF NOT (
        (OLD.statut = 'BROUILLON' AND NEW.statut IN ('BROUILLON', 'SOUMISE', 'ANNULEE'))
        OR
        (OLD.statut = 'SOUMISE' AND NEW.statut IN ('SOUMISE', 'PARTIELLE', 'SERVIE', 'REJETEE'))
        OR
        (OLD.statut = 'PARTIELLE' AND NEW.statut IN ('PARTIELLE', 'SERVIE'))
    ) THEN
        RAISE EXCEPTION 'Transition de statut interne interdite: % vers %.', OLD.statut, NEW.statut;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION emg.fn_ligne_commande_point_modifiable()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_parent_id bigint;
    v_statut varchar(20);
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_parent_id := OLD.idcommande_point_vente;
    ELSE
        v_parent_id := NEW.idcommande_point_vente;
    END IF;

    SELECT statut INTO v_statut
    FROM emg.commande_point_vente
    WHERE id = v_parent_id;

    IF v_statut IS NULL AND TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    IF v_statut = 'BROUILLON' THEN
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;
        RETURN NEW;
    END IF;

    IF TG_OP = 'UPDATE'
       AND v_statut IN ('SOUMISE', 'PARTIELLE')
       AND NEW.idcommande_point_vente = OLD.idcommande_point_vente
       AND NEW.idproduit = OLD.idproduit
       AND NEW.quantite_demandee = OLD.quantite_demandee THEN
        RETURN NEW;
    END IF;

    RAISE EXCEPTION 'Apres soumission, seule la quantite acceptee peut etre modifiee.';
END;
$$;

CREATE TRIGGER trg_commande_point_vente_modifiable
BEFORE UPDATE OR DELETE ON emg.commande_point_vente
FOR EACH ROW EXECUTE FUNCTION emg.fn_commande_point_modifiable();

CREATE TRIGGER trg_ligne_commande_point_modifiable
BEFORE INSERT OR UPDATE OR DELETE ON emg.ligne_commande_point_vente
FOR EACH ROW EXECUTE FUNCTION emg.fn_ligne_commande_point_modifiable();

CREATE TRIGGER trg_livraison_destination
BEFORE INSERT OR UPDATE OF idcommande_point_vente, idpointvente_destination
ON emg.livraison_point_vente
FOR EACH ROW EXECUTE FUNCTION emg.fn_verifier_livraison_destination();

CREATE TRIGGER trg_livraison_modifiable
BEFORE UPDATE OR DELETE ON emg.livraison_point_vente
FOR EACH ROW EXECUTE FUNCTION emg.fn_document_modifiable();

CREATE TRIGGER trg_ligne_livraison_modifiable
BEFORE INSERT OR UPDATE OR DELETE ON emg.ligne_livraison_point_vente
FOR EACH ROW EXECUTE FUNCTION emg.fn_ligne_document_modifiable(
    'livraison_point_vente', 'idlivraison_point_vente'
);

-- ============================================================================
-- Reglement du stock tampon (transfert TAMPON vers NORMAL)
-- ============================================================================

CREATE TABLE emg.transfert_stock_tampon (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference varchar(50) NOT NULL,
    date_transfert date NOT NULL,
    statut varchar(20) NOT NULL DEFAULT 'BROUILLON',
    idoperation_stock bigint,
    idcree_par bigint NOT NULL,
    idvalide_par bigint,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    validated_at timestamptz,
    CONSTRAINT fk_transfert_tampon_operation
        FOREIGN KEY (idoperation_stock) REFERENCES emg.operation_stock(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_transfert_tampon_createur
        FOREIGN KEY (idcree_par) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_transfert_tampon_validateur
        FOREIGN KEY (idvalide_par) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_transfert_tampon_reference UNIQUE (reference),
    CONSTRAINT uq_transfert_tampon_operation UNIQUE (idoperation_stock),
    CONSTRAINT ck_transfert_tampon_statut
        CHECK (statut IN ('BROUILLON', 'VALIDEE', 'ANNULEE')),
    CONSTRAINT ck_transfert_tampon_validation CHECK (
        (statut = 'VALIDEE' AND idoperation_stock IS NOT NULL
                            AND idvalide_par IS NOT NULL
                            AND validated_at IS NOT NULL)
        OR statut IN ('BROUILLON', 'ANNULEE')
    )
);

CREATE TABLE emg.ligne_transfert_stock_tampon (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idtransfert_stock_tampon bigint NOT NULL,
    idproduit bigint NOT NULL,
    quantite bigint NOT NULL,
    CONSTRAINT fk_ligne_transfert_tampon_transfert
        FOREIGN KEY (idtransfert_stock_tampon) REFERENCES emg.transfert_stock_tampon(id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_ligne_transfert_tampon_produit
        FOREIGN KEY (idproduit) REFERENCES emg.produit(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_ligne_transfert_tampon_produit
        UNIQUE (idtransfert_stock_tampon, idproduit),
    CONSTRAINT ck_ligne_transfert_tampon_quantite CHECK (quantite > 0)
);

CREATE INDEX idx_ligne_transfert_tampon_produit
    ON emg.ligne_transfert_stock_tampon (idproduit);

CREATE TRIGGER trg_transfert_tampon_modifiable
BEFORE UPDATE OR DELETE ON emg.transfert_stock_tampon
FOR EACH ROW EXECUTE FUNCTION emg.fn_document_modifiable();

CREATE TRIGGER trg_ligne_transfert_tampon_modifiable
BEFORE INSERT OR UPDATE OR DELETE ON emg.ligne_transfert_stock_tampon
FOR EACH ROW EXECUTE FUNCTION emg.fn_ligne_document_modifiable(
    'transfert_stock_tampon', 'idtransfert_stock_tampon'
);

-- ============================================================================
-- Distributions aux revendeurs
-- ============================================================================

CREATE TABLE emg.distribution_revendeur (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference varchar(50) NOT NULL,
    idrevendeur bigint NOT NULL,
    idpointvente bigint NOT NULL,
    date_distribution date NOT NULL,
    statut varchar(20) NOT NULL DEFAULT 'BROUILLON',
    idoperation_stock bigint,
    idcree_par bigint NOT NULL,
    idvalide_par bigint,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    validated_at timestamptz,
    CONSTRAINT fk_distribution_revendeur
        FOREIGN KEY (idrevendeur) REFERENCES emg.revendeur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_distribution_point_vente
        FOREIGN KEY (idpointvente) REFERENCES emg.point_vente(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_distribution_operation
        FOREIGN KEY (idoperation_stock) REFERENCES emg.operation_stock(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_distribution_createur
        FOREIGN KEY (idcree_par) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_distribution_validateur
        FOREIGN KEY (idvalide_par) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_distribution_reference UNIQUE (reference),
    CONSTRAINT uq_distribution_revendeur_jour UNIQUE (idrevendeur, date_distribution),
    CONSTRAINT uq_distribution_operation UNIQUE (idoperation_stock),
    CONSTRAINT ck_distribution_statut
        CHECK (statut IN ('BROUILLON', 'VALIDEE', 'ANNULEE')),
    CONSTRAINT ck_distribution_validation CHECK (
        (statut = 'VALIDEE' AND idoperation_stock IS NOT NULL
                            AND idvalide_par IS NOT NULL
                            AND validated_at IS NOT NULL)
        OR statut IN ('BROUILLON', 'ANNULEE')
    )
);

CREATE INDEX idx_distribution_point_date
    ON emg.distribution_revendeur (idpointvente, date_distribution);

CREATE TABLE emg.ligne_distribution_revendeur (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iddistribution_revendeur bigint NOT NULL,
    idproduit bigint NOT NULL,
    quantite_initiale bigint NOT NULL DEFAULT 0,
    quantite_ajoutee bigint NOT NULL DEFAULT 0,
    quantite_totale bigint GENERATED ALWAYS AS (
        quantite_initiale + quantite_ajoutee
    ) STORED,
    prix_unitaire numeric(18,2) NOT NULL,
    taux_remise_pct numeric(7,4) NOT NULL DEFAULT 0,
    reduction_fixe numeric(18,2) NOT NULL DEFAULT 0,
    montant_attendu numeric(18,2) GENERATED ALWAYS AS (
        round(((quantite_initiale + quantite_ajoutee)::numeric * prix_unitaire)
              - ((quantite_initiale + quantite_ajoutee)::numeric
                 * prix_unitaire * taux_remise_pct / 100)
              - reduction_fixe, 2)
    ) STORED,
    CONSTRAINT fk_ligne_distribution_distribution
        FOREIGN KEY (iddistribution_revendeur) REFERENCES emg.distribution_revendeur(id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_ligne_distribution_produit
        FOREIGN KEY (idproduit) REFERENCES emg.produit(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_ligne_distribution_produit
        UNIQUE (iddistribution_revendeur, idproduit),
    CONSTRAINT ck_ligne_distribution_quantites CHECK (
        quantite_initiale >= 0
        AND quantite_ajoutee >= 0
        AND quantite_initiale + quantite_ajoutee > 0
    ),
    CONSTRAINT ck_ligne_distribution_prix CHECK (prix_unitaire >= 0),
    CONSTRAINT ck_ligne_distribution_taux CHECK (taux_remise_pct BETWEEN 0 AND 100),
    CONSTRAINT ck_ligne_distribution_reduction CHECK (
        reduction_fixe >= 0 AND montant_attendu >= 0
    )
);

CREATE INDEX idx_ligne_distribution_produit
    ON emg.ligne_distribution_revendeur (idproduit);

CREATE OR REPLACE FUNCTION emg.fn_verifier_distribution_revendeur()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_point_revendeur bigint;
    v_type_point varchar(20);
BEGIN
    SELECT idpointvente INTO v_point_revendeur
    FROM emg.revendeur
    WHERE id = NEW.idrevendeur AND actif = true;

    SELECT type INTO v_type_point
    FROM emg.point_vente
    WHERE id = NEW.idpointvente;

    IF v_point_revendeur IS DISTINCT FROM NEW.idpointvente THEN
        RAISE EXCEPTION 'Le revendeur ne depend pas de ce point de vente.';
    END IF;

    IF v_type_point <> 'POINT_VENTE' THEN
        RAISE EXCEPTION 'Une distribution revendeur doit partir d''un point non central.';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_distribution_revendeur_point
BEFORE INSERT OR UPDATE OF idrevendeur, idpointvente
ON emg.distribution_revendeur
FOR EACH ROW EXECUTE FUNCTION emg.fn_verifier_distribution_revendeur();

CREATE TRIGGER trg_distribution_modifiable
BEFORE UPDATE OR DELETE ON emg.distribution_revendeur
FOR EACH ROW EXECUTE FUNCTION emg.fn_document_modifiable();

CREATE TRIGGER trg_ligne_distribution_modifiable
BEFORE INSERT OR UPDATE OR DELETE ON emg.ligne_distribution_revendeur
FOR EACH ROW EXECUTE FUNCTION emg.fn_ligne_document_modifiable(
    'distribution_revendeur', 'iddistribution_revendeur'
);

-- ============================================================================
-- Situations journalieres
-- ============================================================================

CREATE TABLE emg.situation_revendeur (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iddistribution_revendeur bigint NOT NULL,
    date_situation date NOT NULL,
    statut varchar(20) NOT NULL DEFAULT 'BROUILLON',
    montant_distribue numeric(18,2) NOT NULL DEFAULT 0,
    montant_verse numeric(18,2) NOT NULL DEFAULT 0,
    montant_restant numeric(18,2) NOT NULL DEFAULT 0,
    montant_manquant numeric(18,2) GENERATED ALWAYS AS (
        greatest(montant_distribue - montant_verse - montant_restant, 0)
    ) STORED,
    montant_surplus numeric(18,2) GENERATED ALWAYS AS (
        greatest(montant_verse + montant_restant - montant_distribue, 0)
    ) STORED,
    idcree_par bigint NOT NULL,
    idvalide_par bigint,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    validated_at timestamptz,
    CONSTRAINT fk_situation_revendeur_distribution
        FOREIGN KEY (iddistribution_revendeur) REFERENCES emg.distribution_revendeur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_situation_revendeur_createur
        FOREIGN KEY (idcree_par) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_situation_revendeur_validateur
        FOREIGN KEY (idvalide_par) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_situation_revendeur_distribution UNIQUE (iddistribution_revendeur),
    CONSTRAINT ck_situation_revendeur_statut
        CHECK (statut IN ('BROUILLON', 'VALIDEE', 'ANNULEE')),
    CONSTRAINT ck_situation_revendeur_montants CHECK (
        montant_distribue >= 0 AND montant_verse >= 0 AND montant_restant >= 0
    ),
    CONSTRAINT ck_situation_revendeur_validation CHECK (
        (statut = 'VALIDEE' AND idvalide_par IS NOT NULL AND validated_at IS NOT NULL)
        OR statut IN ('BROUILLON', 'ANNULEE')
    )
);

CREATE INDEX idx_situation_revendeur_date ON emg.situation_revendeur (date_situation);

CREATE TABLE emg.ligne_situation_revendeur (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idsituation_revendeur bigint NOT NULL,
    idproduit bigint NOT NULL,
    quantite_restante bigint NOT NULL,
    prix_unitaire numeric(18,2) NOT NULL,
    montant_restant numeric(18,2) GENERATED ALWAYS AS (
        round(quantite_restante::numeric * prix_unitaire, 2)
    ) STORED,
    CONSTRAINT fk_ligne_situation_revendeur_situation
        FOREIGN KEY (idsituation_revendeur) REFERENCES emg.situation_revendeur(id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_ligne_situation_revendeur_produit
        FOREIGN KEY (idproduit) REFERENCES emg.produit(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_ligne_situation_revendeur_produit
        UNIQUE (idsituation_revendeur, idproduit),
    CONSTRAINT ck_ligne_situation_revendeur_quantite CHECK (quantite_restante >= 0),
    CONSTRAINT ck_ligne_situation_revendeur_prix CHECK (prix_unitaire >= 0)
);

CREATE INDEX idx_ligne_situation_revendeur_produit
    ON emg.ligne_situation_revendeur (idproduit);

CREATE TABLE emg.situation_point_vente (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idpointvente bigint NOT NULL,
    date_situation date NOT NULL,
    statut varchar(20) NOT NULL DEFAULT 'BROUILLON',
    montant_a_justifier numeric(18,2) NOT NULL DEFAULT 0,
    montant_verse numeric(18,2) NOT NULL DEFAULT 0,
    valeur_stock_final numeric(18,2) NOT NULL DEFAULT 0,
    montant_manquant numeric(18,2) GENERATED ALWAYS AS (
        greatest(montant_a_justifier - montant_verse - valeur_stock_final, 0)
    ) STORED,
    montant_surplus numeric(18,2) GENERATED ALWAYS AS (
        greatest(montant_verse + valeur_stock_final - montant_a_justifier, 0)
    ) STORED,
    idcree_par bigint NOT NULL,
    idvalide_par bigint,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    validated_at timestamptz,
    CONSTRAINT fk_situation_point_vente_point
        FOREIGN KEY (idpointvente) REFERENCES emg.point_vente(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_situation_point_vente_createur
        FOREIGN KEY (idcree_par) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_situation_point_vente_validateur
        FOREIGN KEY (idvalide_par) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_situation_point_vente_jour UNIQUE (idpointvente, date_situation),
    CONSTRAINT ck_situation_point_vente_statut
        CHECK (statut IN ('BROUILLON', 'VALIDEE', 'ANNULEE')),
    CONSTRAINT ck_situation_point_vente_montants CHECK (
        montant_a_justifier >= 0 AND montant_verse >= 0 AND valeur_stock_final >= 0
    ),
    CONSTRAINT ck_situation_point_vente_validation CHECK (
        (statut = 'VALIDEE' AND idvalide_par IS NOT NULL AND validated_at IS NOT NULL)
        OR statut IN ('BROUILLON', 'ANNULEE')
    )
);

CREATE INDEX idx_situation_point_vente_date ON emg.situation_point_vente (date_situation);

CREATE TABLE emg.ligne_situation_point_vente (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idsituation_point_vente bigint NOT NULL,
    idproduit bigint NOT NULL,
    stock_initial bigint NOT NULL DEFAULT 0,
    entrees_jour bigint NOT NULL DEFAULT 0,
    sorties_jour bigint NOT NULL DEFAULT 0,
    stock_final bigint NOT NULL DEFAULT 0,
    prix_unitaire numeric(18,2) NOT NULL,
    valeur_stock_final numeric(18,2) GENERATED ALWAYS AS (
        round(stock_final::numeric * prix_unitaire, 2)
    ) STORED,
    CONSTRAINT fk_ligne_situation_point_situation
        FOREIGN KEY (idsituation_point_vente) REFERENCES emg.situation_point_vente(id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_ligne_situation_point_produit
        FOREIGN KEY (idproduit) REFERENCES emg.produit(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_ligne_situation_point_produit
        UNIQUE (idsituation_point_vente, idproduit),
    CONSTRAINT ck_ligne_situation_point_quantites CHECK (
        stock_initial >= 0 AND entrees_jour >= 0 AND sorties_jour >= 0
        AND stock_final >= 0
        AND stock_final = stock_initial + entrees_jour - sorties_jour
    ),
    CONSTRAINT ck_ligne_situation_point_prix CHECK (prix_unitaire >= 0)
);

CREATE INDEX idx_ligne_situation_point_produit
    ON emg.ligne_situation_point_vente (idproduit);

CREATE TRIGGER trg_situation_revendeur_modifiable
BEFORE UPDATE OR DELETE ON emg.situation_revendeur
FOR EACH ROW EXECUTE FUNCTION emg.fn_document_modifiable();

CREATE TRIGGER trg_ligne_situation_revendeur_modifiable
BEFORE INSERT OR UPDATE OR DELETE ON emg.ligne_situation_revendeur
FOR EACH ROW EXECUTE FUNCTION emg.fn_ligne_document_modifiable(
    'situation_revendeur', 'idsituation_revendeur'
);

CREATE TRIGGER trg_situation_point_modifiable
BEFORE UPDATE OR DELETE ON emg.situation_point_vente
FOR EACH ROW EXECUTE FUNCTION emg.fn_document_modifiable();

CREATE TRIGGER trg_ligne_situation_point_modifiable
BEFORE INSERT OR UPDATE OR DELETE ON emg.ligne_situation_point_vente
FOR EACH ROW EXECUTE FUNCTION emg.fn_ligne_document_modifiable(
    'situation_point_vente', 'idsituation_point_vente'
);

-- ============================================================================
-- Versements collectes, manquants et reglements de manquants
-- ============================================================================

CREATE TABLE emg.versement_revendeur (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idsituation_revendeur bigint NOT NULL,
    date_versement timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    montant numeric(18,2) NOT NULL,
    mode_paiement varchar(20) NOT NULL DEFAULT 'ESPECES',
    reference varchar(100),
    idenregistre_par bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_versement_revendeur_situation
        FOREIGN KEY (idsituation_revendeur) REFERENCES emg.situation_revendeur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_versement_revendeur_utilisateur
        FOREIGN KEY (idenregistre_par) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ck_versement_revendeur_montant CHECK (montant > 0),
    CONSTRAINT ck_versement_revendeur_mode CHECK (
        mode_paiement IN ('ESPECES', 'VIREMENT', 'MOBILE_MONEY', 'CHEQUE')
    )
);

CREATE INDEX idx_versement_revendeur_situation
    ON emg.versement_revendeur (idsituation_revendeur);

CREATE TABLE emg.versement_point_vente (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idsituation_point_vente bigint NOT NULL,
    date_versement timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    montant numeric(18,2) NOT NULL,
    mode_paiement varchar(20) NOT NULL DEFAULT 'ESPECES',
    reference varchar(100),
    idenregistre_par bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_versement_point_situation
        FOREIGN KEY (idsituation_point_vente) REFERENCES emg.situation_point_vente(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_versement_point_utilisateur
        FOREIGN KEY (idenregistre_par) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ck_versement_point_montant CHECK (montant > 0),
    CONSTRAINT ck_versement_point_mode CHECK (
        mode_paiement IN ('ESPECES', 'VIREMENT', 'MOBILE_MONEY', 'CHEQUE')
    )
);

CREATE INDEX idx_versement_point_situation
    ON emg.versement_point_vente (idsituation_point_vente);

CREATE TRIGGER trg_versement_revendeur_situation_brouillon
BEFORE INSERT OR UPDATE OR DELETE ON emg.versement_revendeur
FOR EACH ROW EXECUTE FUNCTION emg.fn_ligne_document_modifiable(
    'situation_revendeur', 'idsituation_revendeur'
);

CREATE TRIGGER trg_versement_point_situation_brouillon
BEFORE INSERT OR UPDATE OR DELETE ON emg.versement_point_vente
FOR EACH ROW EXECUTE FUNCTION emg.fn_ligne_document_modifiable(
    'situation_point_vente', 'idsituation_point_vente'
);

CREATE TABLE emg.manquant (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idsituation_revendeur bigint,
    idsituation_point_vente bigint,
    montant_initial numeric(18,2) NOT NULL,
    solde numeric(18,2) NOT NULL,
    statut varchar(20) NOT NULL DEFAULT 'OUVERT',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at timestamptz,
    CONSTRAINT fk_manquant_situation_revendeur
        FOREIGN KEY (idsituation_revendeur) REFERENCES emg.situation_revendeur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_manquant_situation_point
        FOREIGN KEY (idsituation_point_vente) REFERENCES emg.situation_point_vente(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ck_manquant_une_situation CHECK (
        (idsituation_revendeur IS NOT NULL)::integer
        + (idsituation_point_vente IS NOT NULL)::integer = 1
    ),
    CONSTRAINT ck_manquant_montants CHECK (
        montant_initial > 0 AND solde >= 0 AND solde <= montant_initial
    ),
    CONSTRAINT ck_manquant_statut CHECK (statut IN ('OUVERT', 'PARTIEL', 'REGLE')),
    CONSTRAINT ck_manquant_cloture CHECK (
        (statut = 'REGLE' AND solde = 0 AND closed_at IS NOT NULL)
        OR
        (statut <> 'REGLE' AND solde > 0 AND closed_at IS NULL)
    )
);

CREATE UNIQUE INDEX uq_manquant_situation_revendeur
    ON emg.manquant (idsituation_revendeur)
    WHERE idsituation_revendeur IS NOT NULL;

CREATE UNIQUE INDEX uq_manquant_situation_point
    ON emg.manquant (idsituation_point_vente)
    WHERE idsituation_point_vente IS NOT NULL;

CREATE TABLE emg.reglement_manquant (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idmanquant bigint NOT NULL,
    date_reglement timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    montant numeric(18,2) NOT NULL,
    mode_paiement varchar(20) NOT NULL DEFAULT 'ESPECES',
    reference varchar(100),
    idenregistre_par bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reglement_manquant_manquant
        FOREIGN KEY (idmanquant) REFERENCES emg.manquant(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_reglement_manquant_utilisateur
        FOREIGN KEY (idenregistre_par) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ck_reglement_manquant_montant CHECK (montant > 0),
    CONSTRAINT ck_reglement_manquant_mode CHECK (
        mode_paiement IN ('ESPECES', 'VIREMENT', 'MOBILE_MONEY', 'CHEQUE')
    )
);

CREATE INDEX idx_reglement_manquant_manquant
    ON emg.reglement_manquant (idmanquant);

CREATE OR REPLACE FUNCTION emg.fn_initialiser_manquant()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_montant numeric(18,2);
    v_statut varchar(20);
BEGIN
    IF NEW.idsituation_revendeur IS NOT NULL THEN
        SELECT montant_manquant, statut INTO v_montant, v_statut
        FROM emg.situation_revendeur
        WHERE id = NEW.idsituation_revendeur;
    ELSE
        SELECT montant_manquant, statut INTO v_montant, v_statut
        FROM emg.situation_point_vente
        WHERE id = NEW.idsituation_point_vente;
    END IF;

    IF v_statut <> 'VALIDEE' OR v_montant <= 0 THEN
        RAISE EXCEPTION 'Un manquant exige une situation validee avec un ecart negatif.';
    END IF;

    NEW.montant_initial := v_montant;
    NEW.solde := v_montant;
    NEW.statut := 'OUVERT';
    NEW.closed_at := NULL;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION emg.fn_proteger_manquant()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF current_setting('emg.manquant_write_authorized', true) IS DISTINCT FROM 'on' THEN
        RAISE EXCEPTION 'Le manquant est mis a jour uniquement par un reglement.';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION emg.fn_appliquer_reglement_manquant()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_solde numeric(18,2);
    v_nouveau_solde numeric(18,2);
BEGIN
    SELECT solde INTO v_solde
    FROM emg.manquant
    WHERE id = NEW.idmanquant
    FOR UPDATE;

    IF v_solde IS NULL THEN
        RAISE EXCEPTION 'Manquant introuvable.';
    END IF;

    IF NEW.montant > v_solde THEN
        RAISE EXCEPTION 'Le reglement % depasse le solde restant %.', NEW.montant, v_solde;
    END IF;

    v_nouveau_solde := v_solde - NEW.montant;
    PERFORM set_config('emg.manquant_write_authorized', 'on', true);

    UPDATE emg.manquant
       SET solde = v_nouveau_solde,
           statut = CASE WHEN v_nouveau_solde = 0 THEN 'REGLE' ELSE 'PARTIEL' END,
           closed_at = CASE WHEN v_nouveau_solde = 0 THEN CURRENT_TIMESTAMP ELSE NULL END
     WHERE id = NEW.idmanquant;

    PERFORM set_config('emg.manquant_write_authorized', 'off', true);
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_manquant_initialisation
BEFORE INSERT ON emg.manquant
FOR EACH ROW EXECUTE FUNCTION emg.fn_initialiser_manquant();

CREATE TRIGGER trg_manquant_protection
BEFORE UPDATE ON emg.manquant
FOR EACH ROW EXECUTE FUNCTION emg.fn_proteger_manquant();

CREATE TRIGGER trg_manquant_suppression_interdite
BEFORE DELETE ON emg.manquant
FOR EACH ROW EXECUTE FUNCTION emg.fn_ecriture_immutable();

CREATE TRIGGER trg_reglement_manquant_appliquer
BEFORE INSERT ON emg.reglement_manquant
FOR EACH ROW EXECUTE FUNCTION emg.fn_appliquer_reglement_manquant();

CREATE TRIGGER trg_reglement_manquant_immutable
BEFORE UPDATE OR DELETE ON emg.reglement_manquant
FOR EACH ROW EXECUTE FUNCTION emg.fn_ecriture_immutable();

-- ============================================================================
-- Banques, versements aux compagnies et affectations
-- ============================================================================

CREATE TABLE emg.banque (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    designation varchar(150) NOT NULL,
    actif boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_banque_designation_non_vide CHECK (btrim(designation) <> '')
);

CREATE UNIQUE INDEX uq_banque_designation_ci
    ON emg.banque (lower(designation));

CREATE TRIGGER trg_banque_updated_at
BEFORE UPDATE ON emg.banque
FOR EACH ROW EXECUTE FUNCTION emg.fn_set_updated_at();

CREATE TABLE emg.versement_bancaire (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idcompagnie bigint NOT NULL,
    idbanque bigint NOT NULL,
    date_versement date NOT NULL,
    reference varchar(150) NOT NULL,
    motif varchar(255) NOT NULL DEFAULT '',
    montant numeric(18,2) NOT NULL,
    statut varchar(20) NOT NULL DEFAULT 'VALIDEE',
    idenregistre_par bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_versement_bancaire_compagnie
        FOREIGN KEY (idcompagnie) REFERENCES emg.compagnie(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_versement_bancaire_banque
        FOREIGN KEY (idbanque) REFERENCES emg.banque(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_versement_bancaire_utilisateur
        FOREIGN KEY (idenregistre_par) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_versement_bancaire_reference UNIQUE (idbanque, reference),
    CONSTRAINT ck_versement_bancaire_montant CHECK (montant > 0),
    CONSTRAINT ck_versement_bancaire_statut
        CHECK (statut IN ('VALIDEE', 'ANNULEE'))
);

CREATE INDEX idx_versement_bancaire_compagnie_date
    ON emg.versement_bancaire (idcompagnie, date_versement);

CREATE TABLE emg.affectation_versement (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idversement_bancaire bigint NOT NULL,
    idcommande_compagnie bigint NOT NULL,
    montant numeric(18,2) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_affectation_versement
        FOREIGN KEY (idversement_bancaire) REFERENCES emg.versement_bancaire(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_affectation_commande
        FOREIGN KEY (idcommande_compagnie) REFERENCES emg.commande_compagnie(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_affectation_versement_commande
        UNIQUE (idversement_bancaire, idcommande_compagnie),
    CONSTRAINT ck_affectation_versement_montant CHECK (montant > 0)
);

CREATE INDEX idx_affectation_commande
    ON emg.affectation_versement (idcommande_compagnie);

CREATE OR REPLACE FUNCTION emg.fn_verifier_affectation_versement()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_compagnie_versement bigint;
    v_compagnie_commande bigint;
    v_montant_versement numeric(18,2);
    v_total_commande numeric(18,2);
    v_affecte_versement numeric(18,2);
    v_affecte_commande numeric(18,2);
    v_statut_versement varchar(20);
    v_statut_commande varchar(20);
    v_old_id bigint;
BEGIN
    IF TG_OP = 'UPDATE' THEN
        v_old_id := OLD.id;
    ELSE
        v_old_id := NULL;
    END IF;

    SELECT idcompagnie, montant, statut
      INTO v_compagnie_versement, v_montant_versement, v_statut_versement
    FROM emg.versement_bancaire
    WHERE id = NEW.idversement_bancaire
    FOR UPDATE;

    SELECT idcompagnie, statut
      INTO v_compagnie_commande, v_statut_commande
    FROM emg.commande_compagnie
    WHERE id = NEW.idcommande_compagnie;

    IF v_statut_versement <> 'VALIDEE' OR v_statut_commande <> 'VALIDEE' THEN
        RAISE EXCEPTION 'Le versement et la commande doivent etre valides.';
    END IF;

    IF v_compagnie_versement IS DISTINCT FROM v_compagnie_commande THEN
        RAISE EXCEPTION 'Le versement et la commande concernent des compagnies differentes.';
    END IF;

    SELECT coalesce(sum(montant_net), 0) INTO v_total_commande
    FROM emg.ligne_commande_compagnie
    WHERE idcommande_compagnie = NEW.idcommande_compagnie;

    SELECT coalesce(sum(montant), 0) INTO v_affecte_versement
    FROM emg.affectation_versement
    WHERE idversement_bancaire = NEW.idversement_bancaire
      AND (v_old_id IS NULL OR id <> v_old_id);

    SELECT coalesce(sum(montant), 0) INTO v_affecte_commande
    FROM emg.affectation_versement
    WHERE idcommande_compagnie = NEW.idcommande_compagnie
      AND (v_old_id IS NULL OR id <> v_old_id);

    IF v_affecte_versement + NEW.montant > v_montant_versement THEN
        RAISE EXCEPTION 'Les affectations depassent le montant du versement.';
    END IF;

    IF v_affecte_commande + NEW.montant > v_total_commande THEN
        RAISE EXCEPTION 'Les affectations depassent le montant net de la commande.';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_affectation_versement_verification
BEFORE INSERT OR UPDATE ON emg.affectation_versement
FOR EACH ROW EXECUTE FUNCTION emg.fn_verifier_affectation_versement();

-- ============================================================================
-- Objectifs commerciaux
-- ============================================================================

CREATE TABLE emg.objectif_commercial (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idgroupe_produit bigint NOT NULL,
    date_debut date NOT NULL,
    date_fin date NOT NULL,
    montant_cible numeric(18,2) NOT NULL,
    idcree_par bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_objectif_groupe_produit
        FOREIGN KEY (idgroupe_produit) REFERENCES emg.groupe_produit(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_objectif_createur
        FOREIGN KEY (idcree_par) REFERENCES emg.utilisateur(id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_objectif_groupe_periode
        UNIQUE (idgroupe_produit, date_debut, date_fin),
    CONSTRAINT ck_objectif_periode CHECK (date_fin >= date_debut),
    CONSTRAINT ck_objectif_montant CHECK (montant_cible > 0)
);

CREATE INDEX idx_objectif_periode
    ON emg.objectif_commercial (date_debut, date_fin);

CREATE TRIGGER trg_objectif_updated_at
BEFORE UPDATE ON emg.objectif_commercial
FOR EACH ROW EXECUTE FUNCTION emg.fn_set_updated_at();

-- ============================================================================
-- Vues de consultation et de controle
-- ============================================================================

CREATE OR REPLACE VIEW emg.v_stock_detail AS
SELECT s.id,
       pv.designation AS point_vente,
       pv.type AS type_point,
       c.designation AS compagnie,
       gp.designation AS groupe_produit,
       p.designation AS produit,
       s.type_stock,
       s.quantite,
       s.updated_at
FROM emg.stock s
JOIN emg.point_vente pv ON pv.id = s.idpointvente
JOIN emg.produit p ON p.id = s.idproduit
JOIN emg.groupe_produit gp ON gp.id = p.idgroupe_produit
JOIN emg.compagnie c ON c.id = gp.idcompagnie;

CREATE OR REPLACE VIEW emg.v_commande_compagnie_totaux AS
SELECT cc.id AS idcommande_compagnie,
       cc.reference,
       cc.idcompagnie,
       cc.date_commande,
       cc.type_commande,
       cc.statut,
       coalesce(sum(lcc.montant_brut), 0)::numeric(18,2) AS montant_brut,
       coalesce(sum(lcc.montant_reduction), 0)::numeric(18,2) AS montant_reduction,
       coalesce(sum(lcc.montant_net), 0)::numeric(18,2) AS montant_net
FROM emg.commande_compagnie cc
LEFT JOIN emg.ligne_commande_compagnie lcc
       ON lcc.idcommande_compagnie = cc.id
GROUP BY cc.id, cc.reference, cc.idcompagnie, cc.date_commande,
         cc.type_commande, cc.statut;

CREATE OR REPLACE VIEW emg.v_solde_commande_compagnie AS
SELECT vct.*,
       coalesce(sum(av.montant) FILTER (WHERE vb.id IS NOT NULL), 0)::numeric(18,2)
           AS montant_regle,
       (vct.montant_net
        - coalesce(sum(av.montant) FILTER (WHERE vb.id IS NOT NULL), 0))::numeric(18,2)
           AS solde
FROM emg.v_commande_compagnie_totaux vct
LEFT JOIN emg.affectation_versement av
       ON av.idcommande_compagnie = vct.idcommande_compagnie
LEFT JOIN emg.versement_bancaire vb
       ON vb.id = av.idversement_bancaire
      AND vb.statut = 'VALIDEE'
GROUP BY vct.idcommande_compagnie, vct.reference, vct.idcompagnie,
         vct.date_commande, vct.type_commande, vct.statut,
         vct.montant_brut, vct.montant_reduction, vct.montant_net;

CREATE OR REPLACE VIEW emg.v_objectif_realisation AS
SELECT o.id AS idobjectif,
       o.idgroupe_produit,
       o.date_debut,
       o.date_fin,
       o.montant_cible,
       coalesce(sum(lcc.montant_net) FILTER (WHERE cc.id IS NOT NULL), 0)::numeric(18,2)
           AS montant_realise,
       CASE
           WHEN o.montant_cible = 0 THEN 0
           ELSE round(
               coalesce(sum(lcc.montant_net) FILTER (WHERE cc.id IS NOT NULL), 0)
               * 100 / o.montant_cible,
               2
           )
       END::numeric(10,2) AS taux_realisation
FROM emg.objectif_commercial o
LEFT JOIN emg.produit p
       ON p.idgroupe_produit = o.idgroupe_produit
LEFT JOIN emg.ligne_commande_compagnie lcc
       ON lcc.idproduit = p.id
LEFT JOIN emg.commande_compagnie cc
       ON cc.id = lcc.idcommande_compagnie
      AND cc.statut = 'VALIDEE'
      AND cc.date_commande BETWEEN o.date_debut AND o.date_fin
GROUP BY o.id, o.idgroupe_produit, o.date_debut, o.date_fin, o.montant_cible;

CREATE OR REPLACE VIEW emg.v_manquants_ouverts AS
SELECT m.id,
       CASE
           WHEN m.idsituation_revendeur IS NOT NULL THEN 'REVENDEUR'
           ELSE 'POINT_VENTE'
       END AS niveau,
       m.idsituation_revendeur,
       m.idsituation_point_vente,
       m.montant_initial,
       m.solde,
       m.statut,
       m.created_at
FROM emg.manquant m
WHERE m.statut <> 'REGLE';

-- ============================================================================
-- Commentaires utiles pour l'administration
-- ============================================================================

COMMENT ON SCHEMA emg IS
    'Schema metier EMG Manage. Les ecritures validees sont conservees pour audit.';

COMMENT ON TABLE emg.stock IS
    'Solde courant; toute modification doit provenir de mouvement_stock.';

COMMENT ON TABLE emg.mouvement_stock IS
    'Journal immutable des variations de stock avec quantites avant et apres.';

COMMENT ON TABLE emg.transfert_stock_tampon IS
    'Reglement du stock tampon: transfert du TAMPON vers le NORMAL au point central.';

COMMENT ON COLUMN emg.ligne_distribution_revendeur.quantite_initiale IS
    'Restant de la veille deja detenu par le revendeur; ne diminue pas le stock du point.';

COMMENT ON COLUMN emg.ligne_distribution_revendeur.quantite_ajoutee IS
    'Nouvelle quantite remise au revendeur; elle diminue le stock NORMAL du point.';

COMMIT;

-- ============================================================================
-- Donnees initiales a renseigner apres installation
-- ============================================================================
-- Le point CENTRAL doit etre cree avec sa vraie adresse avant tout directeur :
--
-- INSERT INTO emg.point_vente (designation, adresse, type)
-- VALUES ('Direction centrale', '<adresse a completer>', 'CENTRAL');
--
-- Ne jamais inserer un mot de passe utilisateur en clair. Le premier
-- administrateur doit etre cree par Django avec createsuperuser.
