# Generated by Django 6.0.6 on 2026-08-09 01:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0004_distributeur_fond'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SituationJournaliere',
            fields=[
                ('idsituation', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro')),
                ('date_situation', models.DateField(verbose_name='Date de situation')),
                ('fond', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fond')),
                ('montant_total_distribue', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant total distribué')),
                ('montant_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant crédit')),
                ('montant_credit_verse', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Crédit versé')),
                ('montant_vente_verse', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant vente versé')),
                ('montant_total_verse', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant total versé')),
                ('montant_manquant', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant manquant')),
                ('coupures', models.TextField(blank=True, default='', verbose_name='Coupures')),
                ('etat', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('CLOTUREE', 'Clôturée')], default='OUVERTE', max_length=20, verbose_name='Etat')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('distributeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='situations_journalieres', to='referentiel.distributeur', verbose_name='Distributeur')),
                ('point_vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='situations_journalieres', to='referentiel.pointvente', verbose_name='Point de vente')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='situations_journalieres', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Situation journalière',
                'verbose_name_plural': 'Situations journalières',
                'db_table': 'situationjournaliere',
                'ordering': ['-date_situation', '-idsituation'],
            },
        ),
        migrations.CreateModel(
            name='Manquant',
            fields=[
                ('idmanquant', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('reste_a_payer', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reste à payer')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('SOLDE', 'Soldé')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('distributeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manquants', to='referentiel.distributeur', verbose_name='Distributeur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manquants', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('situation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='manquant', to='situations.situationjournaliere', verbose_name='Situation journalière')),
            ],
            options={
                'verbose_name': 'Manquant',
                'verbose_name_plural': 'Manquants',
                'db_table': 'manquant',
                'ordering': ['-date_creation', '-idmanquant'],
            },
        ),
        migrations.CreateModel(
            name='LigneSituationJournaliere',
            fields=[
                ('idlignesituation', models.AutoField(primary_key=True, serialize=False)),
                ('quantite_distribuee', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité distribuée')),
                ('quantite_vendue', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité vendue')),
                ('quantite_restante', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité restante')),
                ('quantite_manquante', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité manquante')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_situations', to='referentiel.produit', verbose_name='Produit')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='situations.situationjournaliere', verbose_name='Situation journalière')),
            ],
            options={
                'verbose_name': 'Ligne situation journalière',
                'verbose_name_plural': 'Lignes situation journalière',
                'db_table': 'lignesituationjournaliere',
                'ordering': ['produit__designation'],
            },
        ),
        migrations.CreateModel(
            name='ReglementManquant',
            fields=[
                ('idreglement', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro')),
                ('date_reglement', models.DateField(verbose_name='Date de règlement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('manquant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglements', to='situations.manquant', verbose_name='Manquant')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglements_manquants', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Règlement manquant',
                'verbose_name_plural': 'Règlements manquants',
                'db_table': 'reglementmanquant',
                'ordering': ['-date_reglement', '-idreglement'],
                'indexes': [models.Index(fields=['manquant'], name='reglementma_manquan_7ffb88_idx'), models.Index(fields=['date_reglement'], name='reglementma_date_re_c3e029_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='situationjournaliere',
            index=models.Index(fields=['date_situation'], name='situationjo_date_si_417c14_idx'),
        ),
        migrations.AddIndex(
            model_name='situationjournaliere',
            index=models.Index(fields=['distributeur'], name='situationjo_distrib_da1dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='situationjournaliere',
            index=models.Index(fields=['point_vente'], name='situationjo_point_v_cea572_idx'),
        ),
        migrations.AddIndex(
            model_name='situationjournaliere',
            index=models.Index(fields=['etat'], name='situationjo_etat_1e6e93_idx'),
        ),
        migrations.AddIndex(
            model_name='manquant',
            index=models.Index(fields=['distributeur'], name='manquant_distrib_a7368a_idx'),
        ),
        migrations.AddIndex(
            model_name='manquant',
            index=models.Index(fields=['statut'], name='manquant_statut_6bebaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='lignesituationjournaliere',
            constraint=models.UniqueConstraint(fields=('situation', 'produit'), name='produit_unique_situation'),
        ),
    ]
