# Generated by Django 6.0.6 on 2026-08-09 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignesituationjournaliere',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire'),
        ),
    ]
