# Generated by Django 6.0.6 on 2026-08-09 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('situations', '0002_lignesituationjournaliere_prix_unitaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignesituationjournaliere',
            name='quantite_manquante',
        ),
    ]
