# Generated by Django 6.0.6 on 2026-08-09 03:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0004_distributeur_fond'),
        ('situations', '0003_remove_lignesituationjournaliere_quantite_manquante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='situationjournaliere',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('distributeur', 'date_situation'), name='situation_unique_distributeur_date_active'),
        ),
    ]
