# Generated by Django 6.0.6 on 2026-08-11 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situations', '0004_situationjournaliere_situation_unique_distributeur_date_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignesituationjournaliere',
            name='taux_remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de remise'),
        ),
    ]
