# Generated by Django 6.0.6 on 2026-07-05 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0002_alter_distributeur_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('DIRECTEUR', 'Directeur'), ('GERANT', 'Gérant')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('point_vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referentiel.pointvente')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profilutilisateur',
            },
        ),
    ]
