# Generated by Django 6.0.6 on 2026-08-14 21:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0004_distributeur_fond'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('idmouvementstock', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numero')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entree de stock'), ('SORTIE', 'Sortie de stock')], max_length=20, verbose_name='Type de mouvement')),
                ('type_stock', models.CharField(choices=[('NORMAL', 'Stock normal'), ('TAMPON', 'Stock tampon')], default='NORMAL', max_length=20, verbose_name='Type de stock')),
                ('date_mouvement', models.DateField(verbose_name='Date du mouvement')),
                ('motif', models.CharField(choices=[('APPROVISIONNEMENT', 'Approvisionnement'), ('RETOUR', 'Retour'), ('AJUSTEMENT', 'Ajustement'), ('CASSE_PERTE', 'Casse / perte'), ('AUTRE', 'Autre')], default='AJUSTEMENT', max_length=40, verbose_name='Motif')),
                ('observation', models.TextField(blank=True, default='', verbose_name='Observation')),
                ('total_quantite', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantite totale')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('point_vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to='referentiel.pointvente', verbose_name='Point de vente')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'db_table': 'mouvementstock',
                'ordering': ['-date_mouvement', '-idmouvementstock'],
            },
        ),
        migrations.CreateModel(
            name='LigneMouvementStock',
            fields=[
                ('idlignemouvementstock', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantite')),
                ('stock_avant', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock avant')),
                ('stock_apres', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock apres')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_mouvements_stock', to='referentiel.produit', verbose_name='Produit')),
                ('mouvement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='mouvements_stock.mouvementstock', verbose_name='Mouvement')),
            ],
            options={
                'verbose_name': 'Ligne mouvement de stock',
                'verbose_name_plural': 'Lignes mouvements de stock',
                'db_table': 'lignemouvementstock',
                'ordering': ['produit__designation'],
            },
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['date_mouvement'], name='mouvementst_date_mo_9428de_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['point_vente'], name='mouvementst_point_v_f742a9_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['type_mouvement'], name='mouvementst_type_mo_a4e324_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['type_stock'], name='mouvementst_type_st_d3716f_idx'),
        ),
        migrations.AddConstraint(
            model_name='lignemouvementstock',
            constraint=models.UniqueConstraint(fields=('mouvement', 'produit'), name='produit_unique_mouvement_stock'),
        ),
    ]
