# Generated by Django 6.0.6 on 2026-07-10 16:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0002_alter_distributeur_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('idstock', models.AutoField(primary_key=True, serialize=False)),
                ('type_stock', models.CharField(choices=[('NORMAL', 'Stock normal'), ('TAMPON', 'Stock tampon')], default='NORMAL', max_length=20, verbose_name='Type de stock')),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité')),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Seuil d'alerte")),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('point_vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='referentiel.pointvente', verbose_name='Point de vente')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='referentiel.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stock',
                'ordering': ['point_vente__designation', 'produit__designation'],
                'indexes': [models.Index(fields=['point_vente'], name='stock_point_v_638c0f_idx'), models.Index(fields=['produit'], name='stock_produit_476494_idx'), models.Index(fields=['type_stock'], name='stock_type_st_22b4be_idx')],
                'constraints': [models.UniqueConstraint(fields=('point_vente', 'produit', 'type_stock'), name='stock_unique')],
            },
        ),
    ]
